import type { Gate } from "../types";

export type CircuitExportPayload = {
  num_qubits: number;
  gates: Array<Record<string, number | string>>;
};

export function circuitToApiPayload(numQubits: number, gates: Gate[]): CircuitExportPayload {
  return {
    num_qubits: numQubits,
    gates: gates.map((g) => {
      if (g.type === "CX") return { type: "CX", control: g.control, target: g.target };
      if (g.type === "RX" || g.type === "RZ")
        return { type: g.type, target: g.target, angle: g.angle };
      return { type: g.type, target: g.target };
    }),
  };
}

export function downloadJson(filename: string, data: unknown) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function gateToPython(g: Gate): string {
  if (g.type === "H") return `qc.h(${g.target})`;
  if (g.type === "X") return `qc.x(${g.target})`;
  if (g.type === "Y") return `qc.y(${g.target})`;
  if (g.type === "Z") return `qc.z(${g.target})`;
  if (g.type === "RX") return `qc.rx(${g.angle}, ${g.target})`;
  if (g.type === "RZ") return `qc.rz(${g.angle}, ${g.target})`;
  return `qc.cx(${g.control}, ${g.target})`;
}

export function buildQiskitScript(numQubits: number, gates: Gate[]): string {
  const lines: string[] = [
    '"""Generated by Quantum Circuit Lab export."""',
    "",
    "from qiskit import QuantumCircuit, transpile",
    "from qiskit_aer import AerSimulator",
    "",
    `n = ${numQubits}`,
    "qc = QuantumCircuit(n)",
    "",
  ];
  if (gates.length === 0) {
    lines.push("# No gates — identity circuit");
  } else {
    lines.push("# Gates");
    for (const g of gates) {
      lines.push(gateToPython(g));
    }
  }
  lines.push(
    "",
    "qc_meas = qc.copy()",
    "qc_meas.measure_all()",
    "sim = AerSimulator()",
    "compiled = transpile(qc_meas, sim)",
    "counts = sim.run(compiled, shots=1000).result().get_counts()",
    'print("counts:", counts)',
  );
  return lines.join("\n");
}

export function downloadText(filename: string, text: string) {
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
